/*
 * The MIT License
 *
 * Copyright 2026 CloudBees, Inc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package com.cloudbees.jenkins.support.filter;

import static org.assertj.core.api.Assertions.assertThat;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.util.List;
import org.junit.jupiter.api.Test;

/**
 * Tests that WordsTrie produces byte-identical regex output to the original tree-based implementation.
 * Rather than committing the old implementation or a megabyte regex file, this test generates a large
 * deterministic word list and compares the SHA-256 hash of the emitted regex against the hash recorded
 * from origin/master's implementation.
 *
 * <p>The golden hash was generated by checking out origin/master's tree-based WordsTrie, running
 * {@link DeterministicWordListGenerator#generate()} through it, and computing the SHA-256 of the
 * emitted regex. This was verified to pass against origin/master on 2026-08-20, then recorded here.
 * The deterministic generator produces 10,100 words covering shared prefixes, prefix-of-prefix chains,
 * duplicates, every regex metacharacter, and surrogate pairs.
 *
 * <p>To regenerate the golden hash: check out {@code origin/master}'s {@code WordsTrie.java},
 * run {@code DeterministicWordListGenerator.generate()} through it, emit the regex, and compute
 * its SHA-256. Compare against the constant below to verify byte-identity.
 */
class GoldenFixtureTest {

    /**
     * SHA-256 hash of the regex emitted by origin/master's tree-based WordsTrie for the deterministic
     * word list from {@link DeterministicWordListGenerator#generate()}.
     * Verified against origin/master on 2026-08-20.
     */
    private static final String GOLDEN_HASH = "7ad4444ec71bb8666657c0eaf9e7dc0883399d3e17ee3d76452fae60ce92d2fc";

    @Test
    void producesbyteIdenticalRegexToOriginMaster() throws Exception {
        List<String> words = DeterministicWordListGenerator.generate();

        WordsTrie trie = new WordsTrie();
        for (String word : words) {
            trie.add(word);
        }

        String regex = trie.getRegex();
        assertThat(regex).isNotNull();

        MessageDigest sha256 = MessageDigest.getInstance("SHA-256");
        byte[] hash = sha256.digest(regex.getBytes(StandardCharsets.UTF_8));
        String actualHash = bytesToHex(hash);

        assertThat(actualHash)
                .as("Regex output must be byte-identical to origin/master's tree-based implementation")
                .isEqualTo(GOLDEN_HASH);
    }

    private static String bytesToHex(byte[] bytes) {
        StringBuilder sb = new StringBuilder();
        for (byte b : bytes) {
            sb.append(String.format("%02x", b));
        }
        return sb.toString();
    }
}
